#!/usr/bin/env python3
"""Build a self-contained manuscript source by recursively inlining local TeX inputs.

The generated file still references external class/style, bibliography, and figure
assets.  Only manuscript content included with ``\\input`` is inlined.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


INPUT_RE = re.compile(r"(?<!%)\\input\s*\{([^}]+)\}")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def resolve_input(root: Path, parent: Path, name: str) -> Path:
    candidate = Path(name)
    if candidate.suffix == "":
        candidate = candidate.with_suffix(".tex")
    # TeX resolves these project-relative inputs from the compilation directory.
    # Retain a parent-relative fallback for conventional nested source layouts.
    root_relative = (root / candidate).resolve()
    parent_relative = (parent / candidate).resolve()
    path = root_relative if root_relative.is_file() else parent_relative
    try:
        path.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"Refusing to inline a path outside the manuscript: {name}") from exc
    if not path.is_file():
        raise FileNotFoundError(f"Missing input file: {path}")
    return path


def inline_file(
    root: Path,
    path: Path,
    stack: tuple[Path, ...],
    manifest: list[dict[str, str]],
) -> str:
    path = path.resolve()
    if path in stack:
        cycle = " -> ".join(str(item.relative_to(root)) for item in (*stack, path))
        raise RuntimeError(f"Cyclic TeX input detected: {cycle}")

    raw = path.read_bytes()
    text = raw.decode("utf-8")
    relative = path.relative_to(root).as_posix()
    manifest.append({"path": relative, "sha256": sha256(raw)})

    def replace(match: re.Match[str]) -> str:
        child = resolve_input(root, path.parent, match.group(1).strip())
        child_relative = child.relative_to(root).as_posix()
        content = inline_file(root, child, (*stack, path), manifest)
        return (
            f"% BEGIN INLINED FILE: {child_relative}\n"
            f"{content.rstrip()}\n"
            f"% END INLINED FILE: {child_relative}"
        )

    return INPUT_RE.sub(replace, text)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=Path.cwd())
    parser.add_argument("--entry", default="main.tex")
    parser.add_argument("--output", default="main_single.tex")
    parser.add_argument("--manifest", default="main_single.manifest.json")
    args = parser.parse_args()

    root = args.source.resolve()
    entry = (root / args.entry).resolve()
    output = (root / args.output).resolve()
    manifest_path = (root / args.manifest).resolve()
    if entry == output:
        raise ValueError("Output must not overwrite the modular entry file")

    files: list[dict[str, str]] = []
    expanded = inline_file(root, entry, (), files)
    remaining = INPUT_RE.findall(expanded)
    if remaining:
        raise RuntimeError(f"Unexpanded TeX inputs remain: {remaining}")

    banner = (
        "% AUTO-GENERATED by scripts/build_single_main_tex.py.\n"
        "% Edit main.tex, sections/*.tex, or tables/*.tex, then regenerate this file.\n"
        "% Class/style, bibliography, and figure assets intentionally remain external.\n"
    )
    output.write_text(banner + expanded, encoding="utf-8")
    output_bytes = output.read_bytes()
    manifest_payload = {
        "entry": entry.relative_to(root).as_posix(),
        "output": output.relative_to(root).as_posix(),
        "output_sha256": sha256(output_bytes),
        "inlined_files_in_expansion_order": files,
    }
    manifest_path.write_text(
        json.dumps(manifest_payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {output}")
    print(f"Recorded {len(files)} source occurrences in {manifest_path}")


if __name__ == "__main__":
    main()
