"""Standard scalar calibrator baselines under the label-free synthetic protocol.

Fits temperature scaling, isotonic regression, histogram binning, and scalar
Platt per (dataset, class, k, seed) cell on exactly the calibration set the
vector calibrators see: the k support normal images (label 0) plus the same
number of synthetic-anomaly images (label 1) generated by the shared
feature-space perturbation (`make_synthetic_feature_batch`). Both sides are
scored with the identical PCA residual top-rho aggregation used everywhere
else, then the fitted mapping is applied to the per-image `raw_score` column
of an existing conformal views CSV, giving per-cell ECE/adaptive ECE under
every corruption without re-running the backbone.

Reusing `raw_score` is exact, not approximate: the views exporter fits
`PCASubspace` on the same cached support features with the same seed and rho,
and that fit is deterministic. `--verify-cells` re-derives clean-test scores
end-to-end for a few cells and asserts the match.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.export_sw_cad_image_views import get_features
from src.calibration.scalar import build_scalar_calibrator
from src.config import load_config
from src.conformal import top_fraction_score
from src.data.datasets import load_records
from src.data.sampling import evaluation_records, few_shot_support
from src.evaluation.metrics import summarize_binary
from src.models.head_pca import make_synthetic_feature_batch
from src.models.pca import PCASubspace

METHODS = ["temperature", "isotonic", "histogram_binning", "scalar_platt"]


def adaptive_ece(labels: np.ndarray, probs: np.ndarray, bins: int = 15) -> float:
    labels = labels.astype(float)
    probs = np.clip(probs.astype(float), 0.0, 1.0)
    if len(labels) == 0:
        return float("nan")
    n_bins = min(bins, len(np.unique(probs)))
    order = np.argsort(probs, kind="stable")
    splits = np.array_split(order, max(1, n_bins))
    ece = 0.0
    for idx in splits:
        if len(idx) == 0:
            continue
        ece += (len(idx) / len(labels)) * abs(probs[idx].mean() - labels[idx].mean())
    return float(ece)


def fit_cell_calibrators(config: dict, dataset: str, cls: str, k: int, seed: int, rho: float, synthetic_ratio: float, pca_components: int) -> dict:
    records = load_records(dataset, f"data/{dataset}", [cls])
    support = few_shot_support(records, k=k, seed=seed)
    backbone_name = config.get("backbone", {}).get("name", "dinov2_vits14")
    support_features = get_features(config, support, f"{dataset}_support_{backbone_name}_k{k}_seed{seed}", seed)
    pca = PCASubspace.fit(support_features, pca_components)
    support_scores = top_fraction_score(pca.residual_scores(support_features), rho=rho)
    synth = make_synthetic_feature_batch(support_features, seed=seed, ratio=synthetic_ratio)
    synth_scores = top_fraction_score(pca.residual_scores(synth), rho=rho)
    cal_scores = np.concatenate([support_scores, synth_scores])
    cal_labels = np.concatenate([np.zeros(len(support_scores)), np.ones(len(synth_scores))])
    fitted = {}
    for name in METHODS:
        calibrator = build_scalar_calibrator(name)
        calibrator.fit(cal_scores, cal_labels)
        fitted[name] = calibrator
    return {"calibrators": fitted, "pca": pca, "n_calibration": int(len(cal_scores))}


def verify_cell(config: dict, views: pd.DataFrame, dataset: str, cls: str, k: int, seed: int, rho: float, pca: PCASubspace, max_images: int | None, tmp_root: str) -> float:
    from scripts.evaluate_corruptions import corrupt_records

    cell_views = views[(views["class"] == cls) & (views.k_shot == k) & (views.seed == seed)]
    if cell_views.empty:
        return float("nan")
    corruptions = sorted(cell_views.corruption.unique())
    corruption = "clean" if "clean" in corruptions else corruptions[0]
    sub = cell_views[cell_views.corruption == corruption]
    records = load_records(dataset, f"data/{dataset}", [cls])
    tmp_dir = Path(tmp_root) / dataset / cls / f"seed{seed}" / corruption
    eval_records = corrupt_records(evaluation_records(records), corruption, tmp_dir, seed=seed, max_images=max_images)
    backbone_name = config.get("backbone", {}).get("name", "dinov2_vits14")
    feats = get_features(config, eval_records, f"{dataset}_corrupt_{cls}_{corruption}_{backbone_name}_seed{seed}", seed, cache_seed=0 if backbone_name.startswith("dinov2") else seed)
    scores = top_fraction_score(pca.residual_scores(feats), rho=rho)
    by_name = {Path(str(r.path)).name: s for r, s in zip(eval_records, scores)}
    diffs = [abs(float(row.raw_score) - by_name[Path(row.image_path).name]) for row in sub.itertuples() if Path(row.image_path).name in by_name]
    if not diffs:
        raise RuntimeError(f"verify: no overlapping image paths for {dataset}/{cls} k={k} seed={seed} corruption={corruption}")
    return float(max(diffs))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--views", required=True, help="Per-image conformal views CSV with raw_score")
    parser.add_argument("--dataset", required=True, choices=["mvtec", "visa"])
    parser.add_argument("--base-config", default="configs/generated/visa_full/calib_subspace_head_visa_candle_k1_seed0.yaml")
    parser.add_argument("--rho", type=float, default=0.01)
    parser.add_argument("--synthetic-ratio", type=float, default=1.0)
    parser.add_argument("--bins", type=int, default=15)
    parser.add_argument("--verify-cells", type=int, default=2, help="Cells to re-derive end-to-end as a raw_score consistency check")
    parser.add_argument("--verify-max-images", type=int, default=120)
    parser.add_argument("--verify-tmp-root", default="/home/crl/AD/tmp/sw_cad_image_views")
    parser.add_argument("--verify-only", action="store_true", help="Run only the raw_score consistency check on --verify-cells cells, then exit")
    parser.add_argument("--out-dir", default="outputs/paper_tables")
    parser.add_argument("--run-tag", required=True)
    args = parser.parse_args()

    config = load_config(args.base_config)
    pca_components = int(config.get("model", {}).get("pca_components", 64))
    views = pd.read_csv(args.views)
    views = views[(views.dataset == args.dataset) & views.label.isin([0, 1])]

    cells = views[["class", "k_shot", "seed"]].drop_duplicates().sort_values(["class", "k_shot", "seed"])
    rows = []
    verified = 0
    for i, cell in enumerate(cells.itertuples(index=False)):
        cls, k, seed = str(cell[0]), int(cell.k_shot), int(cell.seed)
        fit = fit_cell_calibrators(config, args.dataset, cls, k, seed, args.rho, args.synthetic_ratio, pca_components)
        if verified < args.verify_cells:
            max_diff = verify_cell(config, views, args.dataset, cls, k, seed, args.rho, fit["pca"], args.verify_max_images, args.verify_tmp_root)
            if np.isfinite(max_diff):
                if max_diff > 1e-3:
                    raise RuntimeError(f"raw_score mismatch {max_diff:.6f} for {args.dataset}/{cls} k={k} seed={seed}; protocol drift?")
                verified += 1
                print(f"verify_ok cell={cls}/k{k}/s{seed} max_abs_diff={max_diff:.2e}", flush=True)
        if args.verify_only:
            if verified >= args.verify_cells:
                print("verify_only complete")
                return 0
            continue
        cell_views = views[(views["class"] == cls) & (views.k_shot == k) & (views.seed == seed)]
        for corruption, g in cell_views.groupby("corruption"):
            if g.label.nunique() < 2:
                continue
            y = g.label.to_numpy(dtype=np.int64)
            s = g.raw_score.to_numpy(dtype=np.float64)
            for name, calibrator in fit["calibrators"].items():
                probs = calibrator.predict_proba(s)
                metrics = summarize_binary(y, s, probs, bins=args.bins)
                rows.append({
                    "dataset": args.dataset, "class": cls, "k_shot": k, "seed": seed,
                    "corruption": corruption, "method": name,
                    "ece": metrics["ece"], "adaptive_ece": adaptive_ece(y, probs, bins=args.bins),
                    "brier": metrics.get("brier", float("nan")), "nll": metrics.get("nll", float("nan")),
                    "auroc": metrics["auroc"],
                    "n_calibration": fit["n_calibration"], "synthetic_ratio": args.synthetic_ratio,
                })
        print(f"scalar_calibrator_progress={i + 1}/{len(cells)} class={cls} k={k} seed={seed}", flush=True)

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    detailed = pd.DataFrame(rows)
    detailed_path = out / f"scalar_calibrator_baselines_{args.run_tag}_detailed.csv"
    detailed.to_csv(detailed_path, index=False)

    summary = detailed.groupby(["dataset", "k_shot", "corruption", "method"]).agg(
        ece_mean=("ece", "mean"), ece_std=("ece", "std"),
        adaptive_ece_mean=("adaptive_ece", "mean"),
        auroc_mean=("auroc", "mean"), n_cells=("ece", "size"),
    ).reset_index()
    summary.to_csv(out / f"scalar_calibrator_baselines_{args.run_tag}_summary.csv", index=False)

    lines = [
        "# Scalar Calibrator Baselines (label-free synthetic protocol)",
        "",
        f"Calibration set per cell: k support normals + k synthetic anomalies (ratio {args.synthetic_ratio}).",
        "ECE uses 15 equal-width bins; adaptive ECE uses equal-mass bins.",
        "",
        "| dataset | k | corruption | method | ECE mean+/-std | adaptive ECE | AUROC |",
        "|---|---:|---|---|---|---:|---:|",
    ]
    for _, r in summary.iterrows():
        lines.append(
            f"| {r.dataset} | {r.k_shot} | {r.corruption} | {r.method} | "
            f"{r.ece_mean:.4f}+/-{0.0 if pd.isna(r.ece_std) else r.ece_std:.4f} | {r.adaptive_ece_mean:.4f} | {r.auroc_mean:.4f} |"
        )
    (out / f"scalar_calibrator_baselines_{args.run_tag}_summary.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(detailed)} detailed rows to {detailed_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
